### ISSUE TITLE
Crash upon death

### ISSUE THREAD

**Issue by KamiSami** [ArekkuusuJerii/Grimoire-Of-Alice#9]
Also yes i have drunk the hourai elixir, i belive the magic circle is causing issues for some reason... Here:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  MC3ASMCorePlugin ([1.10.2]MetroidCubed3V0.3.30.6.jar)
  ChiselCorePlugin (Chisel_DEV-MC1.10.2-0.0.10.19.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  FirEmerald's Block/Item model renderer API (Block and Item model API 1.0.jar)
  Extended Shaders (Extended Shaders 2.0 [1.10.2].jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  IC2core (industrialcraft-2-2.6.188-ex110.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 4/17/17 2:18 PM
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at arekkuusu.grimoireofalice.common.entity.EntityMagicCircle.getTexture(EntityMagicCircle.java:125)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.getEntityTexture(RenderMagicCircle.java:47)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.func_110775_a(RenderMagicCircle.java:22)
	at net.minecraft.client.renderer.entity.Render.func_180548_c(SourceFile:89)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.doRender(RenderMagicCircle.java:34)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.func_76986_a(RenderMagicCircle.java:22)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at arekkuusu.grimoireofalice.common.entity.EntityMagicCircle.getTexture(EntityMagicCircle.java:125)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.getEntityTexture(RenderMagicCircle.java:47)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.func_110775_a(RenderMagicCircle.java:22)
	at net.minecraft.client.renderer.entity.Render.func_180548_c(SourceFile:89)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.doRender(RenderMagicCircle.java:34)
	at arekkuusu.grimoireofalice.client.render.RenderMagicCircle.func_76986_a(RenderMagicCircle.java:22)

-- Entity being rendered --
Details:
	Entity Type: grimoireofalice.Spell (arekkuusu.grimoireofalice.common.entity.EntityMagicCircle)
	Entity ID: 57773
	Entity Name: entity.grimoireofalice.Spell.name
	Entity's Exact location: 240.75, 74.10, 180.21
	Entity's Block location: World: (240,74,180), Chunk: (at 0,4,4 in 15,11; contains blocks 240,0,176 to 255,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: arekkuusu.grimoireofalice.client.render.RenderMagicCircle@77a92071
	Location: -0.01,0.10,0.01 - World: (-1,0,0), Chunk: (at 15,0,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 79.89639
	Delta: 0.5027895
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kami_Sami'/2833, l='MpServer', x=240.75, y=74.00, z=180.21]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (216,64,256), Chunk: (at 8,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12021656 game time, 12073389 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 101 total; [EntityItem['item.item.rottenFlesh'/51211, l='MpServer', x=211.17, y=86.00, z=138.96], EntitySmallEnergyRefill['Small Energy'/51212, l='MpServer', x=194.52, y=117.30, z=146.90], EntityCreeper['Creeper'/56855, l='MpServer', x=188.50, y=16.00, z=119.50], EntitySkeleton['Skeleton'/56856, l='MpServer', x=190.50, y=16.00, z=120.50], EntityZombie['Zombie'/56857, l='MpServer', x=189.50, y=36.00, z=179.50], EntityZombie['Zombie'/56858, l='MpServer', x=191.50, y=36.00, z=177.50], EntityBat['Bat'/56371, l='MpServer', x=234.53, y=19.75, z=210.09], EntityPlayerSP['Kami_Sami'/2833, l='MpServer', x=240.75, y=74.00, z=180.21], EntityLatchedRenderer['unknown'/55, l='MpServer', x=8.50, y=65.00, z=8.50], EntityCow['Cow'/60, l='MpServer', x=167.84, y=106.00, z=118.32], EntityCow['Cow'/61, l='MpServer', x=176.77, y=99.00, z=129.51], EntityBat['Bat'/54343, l='MpServer', x=176.42, y=48.97, z=253.68], EntitySheep['Sheep'/75, l='MpServer', x=183.55, y=101.00, z=169.50], EntitySheep['Sheep'/76, l='MpServer', x=191.21, y=106.00, z=168.50], EntitySmallEnergyRefill['Small Energy'/49229, l='MpServer', x=244.20, y=153.18, z=229.05], EntityMissileRefill['Missile Refill'/49232, l='MpServer', x=254.83, y=132.67, z=234.00], EntitySheep['Sheep'/85, l='MpServer', x=205.51, y=106.00, z=154.27], EntityCow['Cow'/86, l='MpServer', x=200.26, y=102.00, z=155.49], EntityAshen['Ashen'/54359, l='MpServer', x=239.46, y=23.00, z=219.27], EntitySheep['Sheep'/87, l='MpServer', x=196.64, y=103.00, z=151.94], EntityAshen['Ashen'/54360, l='MpServer', x=236.50, y=18.00, z=211.50], EntitySheep['Sheep'/88, l='MpServer', x=195.45, y=103.00, z=153.18], EntityCow['Cow'/89, l='MpServer', x=195.21, y=100.00, z=164.48], EntitySpider['Spider'/54892, l='MpServer', x=299.50, y=30.00, z=169.50], EntityCreeper['Creeper'/54893, l='MpServer', x=295.50, y=30.00, z=173.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/117, l='MpServer', x=230.50, y=62.50, z=237.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/118, l='MpServer', x=233.50, y=62.50, z=237.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/119, l='MpServer', x=230.50, y=62.50, z=231.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/120, l='MpServer', x=233.50, y=62.50, z=231.50], EntitySkeleton['Skeleton'/53389, l='MpServer', x=244.50, y=29.00, z=227.50], EntityMissileRefill['Missile Refill'/56469, l='MpServer', x=244.65, y=121.17, z=243.72], EntityCreeper['Creeper'/54936, l='MpServer', x=307.50, y=58.00, z=246.50], EntityCreeper['Creeper'/54938, l='MpServer', x=242.56, y=26.00, z=226.20], EntityBat['Bat'/52892, l='MpServer', x=226.22, y=25.59, z=224.64], EntityMissileRefill['Missile Refill'/55972, l='MpServer', x=246.55, y=133.09, z=224.00], EntityItem['item.item.arrow'/39589, l='MpServer', x=238.45, y=79.00, z=149.13], EntitySmallEnergyRefill['Small Energy'/39590, l='MpServer', x=240.73, y=88.14, z=149.22], EntityMissileRefill['Missile Refill'/39591, l='MpServer', x=244.87, y=97.79, z=147.36], EntitySquid['Squid'/48297, l='MpServer', x=233.60, y=58.48, z=212.63], EntityCreeper['Creeper'/53428, l='MpServer', x=249.50, y=28.00, z=221.50], EntitySquid['Squid'/48309, l='MpServer', x=212.40, y=59.80, z=210.25], EntityZombie['Zombie'/55482, l='MpServer', x=291.50, y=55.00, z=129.50], EntityCreeper['Creeper'/55483, l='MpServer', x=318.50, y=31.00, z=179.50], EntityBat['Bat'/54462, l='MpServer', x=163.75, y=52.08, z=190.69], EntityZombie['Zombie'/55488, l='MpServer', x=246.52, y=13.00, z=199.76], EntitySkeleton['Skeleton'/45254, l='MpServer', x=200.81, y=78.00, z=186.69], EntitySmallEnergyRefill['Small Energy'/38608, l='MpServer', x=229.33, y=148.98, z=231.04], EntityMissileRefill['Missile Refill'/32976, l='MpServer', x=240.92, y=89.34, z=154.84], EntitySmallEnergyRefill['Small Energy'/50386, l='MpServer', x=248.40, y=126.46, z=241.81], EntitySquid['Squid'/53459, l='MpServer', x=235.68, y=58.03, z=217.59], EntitySquid['Squid'/53460, l='MpServer', x=227.40, y=56.75, z=208.97], EntitySquid['Squid'/53461, l='MpServer', x=223.44, y=60.97, z=210.87], EntitySquid['Squid'/53462, l='MpServer', x=221.59, y=60.16, z=209.79], EntityBat['Bat'/55536, l='MpServer', x=240.70, y=17.10, z=198.40], EntityBat['Bat'/55538, l='MpServer', x=211.52, y=23.06, z=234.35], EntitySkeleton['Skeleton'/55031, l='MpServer', x=182.50, y=37.00, z=212.50], EntitySkeleton['Skeleton'/55032, l='MpServer', x=182.50, y=37.00, z=214.50], EntityBat['Bat'/52489, l='MpServer', x=224.75, y=13.52, z=209.18], EntitySpark['Spark'/279, l='MpServer', x=261.50, y=73.50, z=191.50], EntitySpark['Spark'/280, l='MpServer', x=260.50, y=73.50, z=188.50], EntitySpark['Spark'/281, l='MpServer', x=261.50, y=73.50, z=187.50], EntitySpark['Spark'/282, l='MpServer', x=260.50, y=73.50, z=186.50], EntitySpark['Spark'/283, l='MpServer', x=259.50, y=73.50, z=187.50], EntityCreeper['Creeper'/46366, l='MpServer', x=163.19, y=57.00, z=210.25], EntityCreeper['Creeper'/53547, l='MpServer', x=236.50, y=26.00, z=221.50], EntityCreeper['Creeper'/53548, l='MpServer', x=238.50, y=26.00, z=219.50], EntityCreeper['Creeper'/53549, l='MpServer', x=236.50, y=26.00, z=221.50], EntitySkeleton['Skeleton'/55096, l='MpServer', x=220.50, y=40.00, z=247.50], EntityBat['Bat'/29497, l='MpServer', x=281.93, y=42.10, z=237.55], EntityBat['Bat'/41794, l='MpServer', x=318.80, y=46.06, z=177.68], EntitySpider['Spider'/55627, l='MpServer', x=317.50, y=57.00, z=238.50], EntityCow['Cow'/338, l='MpServer', x=303.46, y=111.00, z=158.81], EntityCreeper['Creeper'/48979, l='MpServer', x=216.50, y=40.00, z=253.50], EntitySkeleton['Skeleton'/54623, l='MpServer', x=289.50, y=7.00, z=165.70], EntityCreeper['Creeper'/54624, l='MpServer', x=289.50, y=7.00, z=164.74], EntityWitch['Witch'/51041, l='MpServer', x=296.50, y=39.00, z=236.50], EntityCreeper['Creeper'/51043, l='MpServer', x=300.50, y=39.00, z=238.50], EntityCow['Cow'/359, l='MpServer', x=307.82, y=91.00, z=169.45], EntitySkeleton['Skeleton'/50535, l='MpServer', x=270.50, y=40.00, z=187.50], EntityCow['Cow'/360, l='MpServer', x=305.52, y=98.00, z=164.77], EntityMissileRefill['Missile Refill'/35688, l='MpServer', x=209.83, y=135.39, z=243.12], EntitySheep['Sheep'/363, l='MpServer', x=307.23, y=69.00, z=216.81], EntityPig['Pig'/364, l='MpServer', x=304.12, y=70.00, z=228.35], EntitySkeleton['Skeleton'/55154, l='MpServer', x=315.50, y=51.00, z=165.50], EntityCreeper['Creeper'/55155, l='MpServer', x=319.50, y=51.00, z=167.50], EntityCreeper['Creeper'/50036, l='MpServer', x=293.50, y=53.00, z=133.50], EntitySkeleton['Skeleton'/50037, l='MpServer', x=289.50, y=53.00, z=135.50], EntityBat['Bat'/55672, l='MpServer', x=268.42, y=31.03, z=221.53], EntityVillager['Villager'/380, l='MpServer', x=319.92, y=67.00, z=170.70], EntityVillager['Villager'/381, l='MpServer', x=319.92, y=67.00, z=170.70], EntityZombie['Zombie'/55206, l='MpServer', x=297.50, y=13.00, z=128.50], EntityZombie['Zombie'/55207, l='MpServer', x=242.50, y=29.00, z=233.50], EntityZombie['Zombie'/55208, l='MpServer', x=240.50, y=29.00, z=233.50], EntityMagicCircle['entity.grimoireofalice.Spell.name'/57773, l='MpServer', x=240.75, y=74.10, z=180.21], EntityZombie['Zombie'/55733, l='MpServer', x=292.50, y=16.00, z=121.50], EntityZombie['Zombie'/52674, l='MpServer', x=309.50, y=34.00, z=253.50], EntitySkeleton['Skeleton'/53213, l='MpServer', x=313.50, y=50.00, z=166.50], EntityCreeper['Creeper'/55262, l='MpServer', x=177.50, y=43.00, z=244.50], EntityBat['Bat'/56827, l='MpServer', x=297.69, y=17.02, z=134.34], EntitySpider['Spider'/54781, l='MpServer', x=241.99, y=29.00, z=226.99], EntitySpider['Spider'/54782, l='MpServer', x=244.09, y=29.00, z=229.09]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/55, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1347581960 bytes (1285 MB) / 4282384384 bytes (4084 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	MC3ASMCore{0.1} [Metroid Cubed 3 ASM Core] (minecraft.jar) 
	UCHIJA	FERAPI{1.0} [FirEmerald's Block/Item model API] (minecraft.jar) 
	UCHIJA	extendedshaders{2.0} [Extended Shaders] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHIJA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJA	mc3{0.3.30.6} [Metroid Cubed 3] ([1.10.2]MetroidCubed3V0.3.30.6.jar) 
	UCHIJA	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCHIJA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	badwithernocookie{1.10.2-0.0.1-5418dde} [Bad Wither No Cookie!] (BadWitherNoCookie-1.10.2-0.0.1-5418dde.jar) 
	UCHIJA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJA	BloodMagic{1.10.2-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.9-78.jar) 
	UCHIJA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UCHIJA	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHIJA	brandonscore{2.1.6} [Brandon's Core] (BrandonsCore-1.10.2-2.1.6.98-universal.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.10.19} [Chisel] (Chisel_DEV-MC1.10.2-0.0.10.19.jar) 
	UCHIJA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJA	IC2{2.6.188-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.188-ex110.jar) 
	UCHIJA	compactsolars{1.10.2-5.0.8.331} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.8.331-universal.jar) 
	UCHIJA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJA	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJA	danmakucore{1.10.2-0.2.0-3} [DanmakuCore] (danmakucore-1.10.2-0.2.0-3.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	darkutils{1.1.7.111} [Dark Utilities] (DarkUtilities-1.10.2-1.1.7.111.jar) 
	UCHIJA	forestry{5.2.17.373} [Forestry] (forestry_1.10.2-5.2.17.373.jar) 
	UCHIJA	eleccore{1.7.415} [ElecCore] (ElecCore-1.10.2-1.7.415.jar) 
	UCHIJA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJA	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UCHIJA	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJA	draconicevolution{2.0.10} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.10.193-universal.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.180} [Ender IO] (EnderIO-1.10.2-3.1.180.jar) 
	UCHIJA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJA	zerocore{1.10.2-0.1.0.5} [Zero CORE] (zerocore-1.10.2-0.1.0.5.jar) 
	UCHIJA	bigreactors{1.10.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.28.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCHIJA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCHIJA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UCHIJA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJA	ichunutil{6.3.0} [iChunUtil] (iChunUtil-1.10.2-6.3.0.jar) 
	UCHIJA	gravitygun{6.0.0} [GravityGun] (GravityGun-1.10.2-6.0.0.jar) 
	UCHIJA	grimoireofalice{0.2.9} [Grimoire of Alice] (GrimoireofAlice-0.2.9.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJA	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHIJA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJA	inventorysorter{0.11.0+47} [Simple Inventory sorting] (inventorysorter-1.10.2-0.11.0+47.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.25} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.25.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UCHIJA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJA	mercurius{1.0.3} [Mercurius] (Mercurius-1.10.2-1.0.3.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJA	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	possessed{1.0.0} [Possessed] (possessed-1.0.0.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJA	redstonearsenal{2.0.3} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.3.29-universal.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.7.1} [Storage Drawers] (StorageDrawers-1.10.2-3.7.1.jar) 
	UCHIJA	refinedstorage{1.2.25} [Refined Storage] (refinedstorage-1.2.25.jar) 
	UCHIJA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJA	rftools{5.91} [RFTools] (rftools-1.1x-5.91.jar) 
	UCHIJA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJA	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar) 
	UCHIJA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJA	xnet{1.1.5} [XNet] (xnet-1.1.5.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
MC3ASMCorePlugin ([1.10.2]MetroidCubed3V0.3.30.6.jar)
  metroidcubed3.asm.MC3ASMCommon
  metroidcubed3.asm.MC3ASMClient
ChiselCorePlugin (Chisel_DEV-MC1.10.2-0.0.10.19.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
FirEmerald's Block/Item model renderer API (Block and Item model API 1.0.jar)
  firemerald.renderapi.Transformer
Extended Shaders (Extended Shaders 2.0 [1.10.2].jar)
  extendedshaders.core.TransformerOb
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
IC2core (industrialcraft-2-2.6.188-ex110.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.92' Renderer: 'GeForce GTX 980/PCIe/SSE2'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/E:/Minecraft%20Curse%20Client/Instances/FTB%20Presents%20Direwolf20%201.10/mods/%5B1.10.2%5DMetroidCubed3V0.3.30.6.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON
	Launched Version: forge-12.18.3.2254
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.92, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Metroid Cubed 3 Background Music.zip (incompatible), Prime.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by BunnyCinnamon** [comment]
Oh dear lord.... Im sorrry!!!! I fixed this ages ago, but I still need DanmakuCore to update. I will let you know when I publish the new version :<

**Comment by KamiSami** [comment]
Alright, that's cool. The mod has a lot of potential, can't wait to see future updates. :D Also one bug that might be worth of checking: Going F5 mode while it is raining when you have holy shimenawa rope equipped makes your screen white.

**Comment by BunnyCinnamon** [comment]
Ok, its fixed

**Comment by BunnyCinnamon** [comment]
Aaaaand, the Rope thing happens when you use Fast Graphics

**Comment by KamiSami** [comment]
Nope, i use fancy graphics and it still happens. Also, thanks for the magic circle fix. :D
